version: '3.7'

services:
  fixclient:
    image: 'sarychev90/fix:client'
    build:
       context: .
       dockerfile: ./fixClient/Dockerfile
    ports:
      - 8081:8081
    container_name: fixclient
    depends_on:
      - fixserver
  fixserver:
    image: 'sarychev90/fix:server'
    build:
       context: .
       dockerfile: ./fixServer/Dockerfile
    ports:
      - 9876:9876
      - 9877:9877
      - 9878:9878
      - 9879:9879
      - 9880:9880
      - 9881:9881
    container_name: fixserver  